//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debts.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Debts.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Tutorial_Debts_Title {
            get {
                return ResourceManager.GetString("Tutorial_Debts_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_Debts_Description {
            get {
                return ResourceManager.GetString("Tutorial_Debts_Description", resourceCulture);
            }
        }
        
        public static string Tutorial_Budget_Title {
            get {
                return ResourceManager.GetString("Tutorial_Budget_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_Budget_Description {
            get {
                return ResourceManager.GetString("Tutorial_Budget_Description", resourceCulture);
            }
        }
        
        public static string Tutorial_PhoneContacts_Title {
            get {
                return ResourceManager.GetString("Tutorial_PhoneContacts_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_PhoneContacts_Description {
            get {
                return ResourceManager.GetString("Tutorial_PhoneContacts_Description", resourceCulture);
            }
        }
        
        public static string Tutorial_GpsTracking_Title {
            get {
                return ResourceManager.GetString("Tutorial_GpsTracking_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_GpsTracking_Description {
            get {
                return ResourceManager.GetString("Tutorial_GpsTracking_Description", resourceCulture);
            }
        }
        
        public static string Tutorial_NotifyDebtors_Title {
            get {
                return ResourceManager.GetString("Tutorial_NotifyDebtors_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_NotifyDebtors_Description {
            get {
                return ResourceManager.GetString("Tutorial_NotifyDebtors_Description", resourceCulture);
            }
        }
        
        public static string Tutorial_More_Title {
            get {
                return ResourceManager.GetString("Tutorial_More_Title", resourceCulture);
            }
        }
        
        public static string Tutorial_More_Description {
            get {
                return ResourceManager.GetString("Tutorial_More_Description", resourceCulture);
            }
        }
        
        public static string Command_CallContact_PermissionRequired {
            get {
                return ResourceManager.GetString("Command_CallContact_PermissionRequired", resourceCulture);
            }
        }
        
        public static string Command_DeleteContact_QuestionDialog_Title {
            get {
                return ResourceManager.GetString("Command_DeleteContact_QuestionDialog_Title", resourceCulture);
            }
        }
        
        public static string Command_DeleteContact_QuestionDialog_Content {
            get {
                return ResourceManager.GetString("Command_DeleteContact_QuestionDialog_Content", resourceCulture);
            }
        }
        
        public static string Command_AddNoteEmptyText_ToastErrorContent {
            get {
                return ResourceManager.GetString("Command_AddNoteEmptyText_ToastErrorContent", resourceCulture);
            }
        }
        
        public static string Command_AddContact_ToastErrorContent {
            get {
                return ResourceManager.GetString("Command_AddContact_ToastErrorContent", resourceCulture);
            }
        }
        
        public static string Command_TransferToImportContact_ToastPermission_Content {
            get {
                return ResourceManager.GetString("Command_TransferToImportContact_ToastPermission_Content", resourceCulture);
            }
        }
        
        public static string Command_TransferToImportContact_ToastPermission_ActionText {
            get {
                return ResourceManager.GetString("Command_TransferToImportContact_ToastPermission_ActionText", resourceCulture);
            }
        }
        
        public static string Command_DeleteFinanceOperation_QuestionDialog_Title {
            get {
                return ResourceManager.GetString("Command_DeleteFinanceOperation_QuestionDialog_Title", resourceCulture);
            }
        }
        
        public static string Command_DeleteBudgetOperation_QuestionDialog_Title {
            get {
                return ResourceManager.GetString("Command_DeleteBudgetOperation_QuestionDialog_Title", resourceCulture);
            }
        }
        
        public static string Command_DeleteFinanceOperation_QuestionDialog_Content {
            get {
                return ResourceManager.GetString("Command_DeleteFinanceOperation_QuestionDialog_Content", resourceCulture);
            }
        }
        
        public static string Command_DeleteBudget_QuestionDialog_Content {
            get {
                return ResourceManager.GetString("Command_DeleteBudget_QuestionDialog_Content", resourceCulture);
            }
        }
        
        public static string Command_FinalizeFinanceOperation_QuestionDialog_Title {
            get {
                return ResourceManager.GetString("Command_FinalizeFinanceOperation_QuestionDialog_Title", resourceCulture);
            }
        }
        
        public static string Command_FinalizeFinanceOperation_QuestionDialog_Content {
            get {
                return ResourceManager.GetString("Command_FinalizeFinanceOperation_QuestionDialog_Content", resourceCulture);
            }
        }
        
        public static string Command_AddNewFinanceOperation_QuestionDialog_Title {
            get {
                return ResourceManager.GetString("Command_AddNewFinanceOperation_QuestionDialog_Title", resourceCulture);
            }
        }
        
        public static string Command_AddNewFinanceOperation_QuestionDialog_Content {
            get {
                return ResourceManager.GetString("Command_AddNewFinanceOperation_QuestionDialog_Content", resourceCulture);
            }
        }
        
        public static string Command_ListDeleteFinanceOperation_ToastContent {
            get {
                return ResourceManager.GetString("Command_ListDeleteFinanceOperation_ToastContent", resourceCulture);
            }
        }
        
        public static string Command_ListDeleteBudget_ToastContent {
            get {
                return ResourceManager.GetString("Command_ListDeleteBudget_ToastContent", resourceCulture);
            }
        }
        
        public static string Command_ListFinalizeFinanceOperation_ToastContent {
            get {
                return ResourceManager.GetString("Command_ListFinalizeFinanceOperation_ToastContent", resourceCulture);
            }
        }
        
        public static string Toast_ActionText_Undo {
            get {
                return ResourceManager.GetString("Toast_ActionText_Undo", resourceCulture);
            }
        }
        
        public static string Converters_AppDomain_FinancesViewModelToDateRangeValueConverter_ForDatePeriod {
            get {
                return ResourceManager.GetString("Converters_AppDomain_FinancesViewModelToDateRangeValueConverter_ForDatePeriod", resourceCulture);
            }
        }
        
        public static string Converters_FinanceOperationPaymentDateTextValueConverter_PaymentHasNotBeenMadeText {
            get {
                return ResourceManager.GetString("Converters_FinanceOperationPaymentDateTextValueConverter_PaymentHasNotBeenMadeTex" +
                        "t", resourceCulture);
            }
        }
        
        public static string Converters_PickedContactToTextValueConverter_TapToPickContactText {
            get {
                return ResourceManager.GetString("Converters_PickedContactToTextValueConverter_TapToPickContactText", resourceCulture);
            }
        }
        
        public static string Converters_PickedBudgetCategoryToTextValueConverter_TapToPickBudgetCategoryText {
            get {
                return ResourceManager.GetString("Converters_PickedBudgetCategoryToTextValueConverter_TapToPickBudgetCategoryText", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_OperationTitleMissing {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_OperationTitleMissing", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_ContactMissing {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_ContactMissing", resourceCulture);
            }
        }
        
        public static string ViewModel_AddBudgetViewModel_CategoryMissing {
            get {
                return ResourceManager.GetString("ViewModel_AddBudgetViewModel_CategoryMissing", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_OperationAmountMissing {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_OperationAmountMissing", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_PaymentDateMissing {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_PaymentDateMissing", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_EnterOperationTitle {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_EnterOperationTitle", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_EnterContact {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_EnterContact", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_EnterOperationAmount {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_EnterOperationAmount", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperationViewModel_EnterPaymentDate {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperationViewModel_EnterPaymentDate", resourceCulture);
            }
        }
        
        public static string ViewModel_AddFinanceOperatioNViewModel_EnterTitleHint {
            get {
                return ResourceManager.GetString("ViewModel_AddFinanceOperatioNViewModel_EnterTitleHint", resourceCulture);
            }
        }
        
        public static string ViewModel_FinancesDetailsViewModel_Notes {
            get {
                return ResourceManager.GetString("ViewModel_FinancesDetailsViewModel_Notes", resourceCulture);
            }
        }
        
        public static string ViewModel_FinanceDetailsViewModel_NoNotes {
            get {
                return ResourceManager.GetString("ViewModel_FinanceDetailsViewModel_NoNotes", resourceCulture);
            }
        }
        
        public static string ViewModel_FinancesDetailsViewModel_Note_CallDone {
            get {
                return ResourceManager.GetString("ViewModel_FinancesDetailsViewModel_Note_CallDone", resourceCulture);
            }
        }
        
        public static string ViewModel_FinanceDetailsViewModel_Note_AskIfShared {
            get {
                return ResourceManager.GetString("ViewModel_FinanceDetailsViewModel_Note_AskIfShared", resourceCulture);
            }
        }
        
        public static string ViewModel_FinanceDetailsViewModel_Note_AskIfSms {
            get {
                return ResourceManager.GetString("ViewModel_FinanceDetailsViewModel_Note_AskIfSms", resourceCulture);
            }
        }
        
        public static string ViewModel_FinanceDetailsViewModel_Note_YouHaveShared {
            get {
                return ResourceManager.GetString("ViewModel_FinanceDetailsViewModel_Note_YouHaveShared", resourceCulture);
            }
        }
        
        public static string ViewModel_FinanceDetailsViewModel_Note_YouHaveSentSms {
            get {
                return ResourceManager.GetString("ViewModel_FinanceDetailsViewModel_Note_YouHaveSentSms", resourceCulture);
            }
        }
        
        public static string ViewModel_ContactListViewModel_Dialog_ImportContacts_Title {
            get {
                return ResourceManager.GetString("ViewModel_ContactListViewModel_Dialog_ImportContacts_Title", resourceCulture);
            }
        }
        
        public static string ViewModel_ContactListViewModel_Dialog_ImportContacts_Content {
            get {
                return ResourceManager.GetString("ViewModel_ContactListViewModel_Dialog_ImportContacts_Content", resourceCulture);
            }
        }
        
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        public static string ActiveDebts {
            get {
                return ResourceManager.GetString("ActiveDebts", resourceCulture);
            }
        }
        
        public static string ActiveLoans {
            get {
                return ResourceManager.GetString("ActiveLoans", resourceCulture);
            }
        }
        
        public static string PastTransactions {
            get {
                return ResourceManager.GetString("PastTransactions", resourceCulture);
            }
        }
        
        public static string MultipleCurrencies {
            get {
                return ResourceManager.GetString("MultipleCurrencies", resourceCulture);
            }
        }
        
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        public static string Dialog_Error_Title {
            get {
                return ResourceManager.GetString("Dialog_Error_Title", resourceCulture);
            }
        }
        
        public static string Dialog_Error_DateFilterFinances_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_DateFilterFinances_Content", resourceCulture);
            }
        }
        
        public static string Dialog_Error_EndDateFilterFinances_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_EndDateFilterFinances_Content", resourceCulture);
            }
        }
        
        public static string Dialog_Error_DateFilterStatistics_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_DateFilterStatistics_Content", resourceCulture);
            }
        }
        
        public static string Dialog_Error_EndDateFilterStatistics_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_EndDateFilterStatistics_Content", resourceCulture);
            }
        }
        
        public static string Dialog_Error_AtLeastOnFilter_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_AtLeastOnFilter_Content", resourceCulture);
            }
        }
        
        public static string Dialog_Error_FilterCategory_Content {
            get {
                return ResourceManager.GetString("Dialog_Error_FilterCategory_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Statistics_FilterByDate_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Statistics_FilterByDate_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Statistics_FilterByDate_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Statistics_FilterByDate_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_AddOperation_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_AddOperation_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_AddOperation_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_AddOperation_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_FilterByDate_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_FilterByDate_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_FilterByCategory_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_FilterByCategory_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_FilterByDate_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_FilterByDate_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Budget_FilterByCategory_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Budget_FilterByCategory_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_AddOperation_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_AddOperation_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_AddOperation_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_AddOperation_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_Menu_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_Menu_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_Menu_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_Menu_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_FilterByDate_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_FilterByDate_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_FilterByDate_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_FilterByDate_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_FilterByStatus_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_FilterByStatus_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_Main_FilterByStatus_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_Main_FilterByStatus_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ImportContacts_LookingForContact_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_ImportContacts_LookingForContact_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ImportContacts_LookingForContact_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_ImportContacts_LookingForContact_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ImportContacts_Utilities_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_ImportContacts_Utilities_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ImportContacts_Utilities_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_ImportContacts_Utilities_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_FinalizeOperation_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_FinalizeOperation_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_FinalizeOperation_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_FinalizeOperation_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_AddNote_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_AddNote_Title", resourceCulture);
            }
        }
        
        public static string WalkthrougService_FinanceDetails_AddNote_Content {
            get {
                return ResourceManager.GetString("WalkthrougService_FinanceDetails_AddNote_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_PhoneCall_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_PhoneCall_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_PhoneCall_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_PhoneCall_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_SMS_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_SMS_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_SMS_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_SMS_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_Share_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_Share_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_Share_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_Share_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_FavoriteOperation_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_FavoriteOperation_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_FinanceDetails_FavoriteOperation_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_FinanceDetails_FavoriteOperation_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ContactList_AddContact_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_ContactList_AddContact_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ContactList_AddContact_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_ContactList_AddContact_Content", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ContactList_ImportContact_Title {
            get {
                return ResourceManager.GetString("WalkthroughService_ContactList_ImportContact_Title", resourceCulture);
            }
        }
        
        public static string WalkthroughService_ContactList_ImportContact_Content {
            get {
                return ResourceManager.GetString("WalkthroughService_ContactList_ImportContact_Content", resourceCulture);
            }
        }
        
        public static string Notifications_UpcomingDebt {
            get {
                return ResourceManager.GetString("Notifications_UpcomingDebt", resourceCulture);
            }
        }
        
        public static string Notifications_UpcomingLoan {
            get {
                return ResourceManager.GetString("Notifications_UpcomingLoan", resourceCulture);
            }
        }
        
        public static string Notifications_UnpaidDebt {
            get {
                return ResourceManager.GetString("Notifications_UnpaidDebt", resourceCulture);
            }
        }
        
        public static string Notifications_UnpaidLoan {
            get {
                return ResourceManager.GetString("Notifications_UnpaidLoan", resourceCulture);
            }
        }
        
        public static string Notifications_Template_UpcomingDebt {
            get {
                return ResourceManager.GetString("Notifications_Template_UpcomingDebt", resourceCulture);
            }
        }
        
        public static string Notifications_Template_UpcomingLoan {
            get {
                return ResourceManager.GetString("Notifications_Template_UpcomingLoan", resourceCulture);
            }
        }
        
        public static string Notifications_Template_UnpaidDebt {
            get {
                return ResourceManager.GetString("Notifications_Template_UnpaidDebt", resourceCulture);
            }
        }
        
        public static string Notifications_Template_UnpaidLoan {
            get {
                return ResourceManager.GetString("Notifications_Template_UnpaidLoan", resourceCulture);
            }
        }
        
        public static string ContactList_Title {
            get {
                return ResourceManager.GetString("ContactList_Title", resourceCulture);
            }
        }
        
        public static string PickBudgetCategory_Title {
            get {
                return ResourceManager.GetString("PickBudgetCategory_Title", resourceCulture);
            }
        }
        
        public static string PickContact_Title {
            get {
                return ResourceManager.GetString("PickContact_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Title", resourceCulture);
            }
        }
        
        public static string AddBudget_Title {
            get {
                return ResourceManager.GetString("AddBudget_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_NEXT {
            get {
                return ResourceManager.GetString("AddFinanceOperation_NEXT", resourceCulture);
            }
        }
        
        public static string AddBudget_NEXT {
            get {
                return ResourceManager.GetString("AddBudget_NEXT", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_1_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_1_Title", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_1_Title {
            get {
                return ResourceManager.GetString("AddBudget_Page_1_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_1_Content {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_1_Content", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_1_Content {
            get {
                return ResourceManager.GetString("AddBudget_Page_1_Content", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_2_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_2_Title", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_2_Title {
            get {
                return ResourceManager.GetString("AddBudget_Page_2_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_2_Content {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_2_Content", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_2_Content {
            get {
                return ResourceManager.GetString("AddBudget_Page_2_Content", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_3_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_3_Title", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_3_Title {
            get {
                return ResourceManager.GetString("AddBudget_Page_3_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_3_Content {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_3_Content", resourceCulture);
            }
        }
        
        public static string AddBudget_Page_3_Content {
            get {
                return ResourceManager.GetString("AddBudget_Page_3_Content", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_4_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_4_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperation_Page_4_Content {
            get {
                return ResourceManager.GetString("AddFinanceOperation_Page_4_Content", resourceCulture);
            }
        }
        
        public static string BudgetList_EmptyListText {
            get {
                return ResourceManager.GetString("BudgetList_EmptyListText", resourceCulture);
            }
        }
        
        public static string IncomeBudgetList_EmptyListText {
            get {
                return ResourceManager.GetString("IncomeBudgetList_EmptyListText", resourceCulture);
            }
        }
        
        public static string ExpenseBudgetList_EmptyListText {
            get {
                return ResourceManager.GetString("ExpenseBudgetList_EmptyListText", resourceCulture);
            }
        }
        
        public static string BudgetList_Title {
            get {
                return ResourceManager.GetString("BudgetList_Title", resourceCulture);
            }
        }
        
        public static string BudgetIncome_Title {
            get {
                return ResourceManager.GetString("BudgetIncome_Title", resourceCulture);
            }
        }
        
        public static string BudgetExpense_Title {
            get {
                return ResourceManager.GetString("BudgetExpense_Title", resourceCulture);
            }
        }
        
        public static string AllFinancesList_Title {
            get {
                return ResourceManager.GetString("AllFinancesList_Title", resourceCulture);
            }
        }
        
        public static string AllFinancesList_EmptyListText {
            get {
                return ResourceManager.GetString("AllFinancesList_EmptyListText", resourceCulture);
            }
        }
        
        public static string FavoriteFinanceList_Title {
            get {
                return ResourceManager.GetString("FavoriteFinanceList_Title", resourceCulture);
            }
        }
        
        public static string FavoriteFinanceList_EmptyListText {
            get {
                return ResourceManager.GetString("FavoriteFinanceList_EmptyListText", resourceCulture);
            }
        }
        
        public static string MyDebts_EmptyListText {
            get {
                return ResourceManager.GetString("MyDebts_EmptyListText", resourceCulture);
            }
        }
        
        public static string MyLoans_EmptyListText {
            get {
                return ResourceManager.GetString("MyLoans_EmptyListText", resourceCulture);
            }
        }
        
        public static string ImportContactsViewModel_FetchingContactsText {
            get {
                return ResourceManager.GetString("ImportContactsViewModel.FetchingContactsText", resourceCulture);
            }
        }
        
        public static string ImportContactsViewModel_EmptyListText {
            get {
                return ResourceManager.GetString("ImportContactsViewModel.EmptyListText", resourceCulture);
            }
        }
        
        public static string StartViewModel_Start {
            get {
                return ResourceManager.GetString("StartViewModel.Start", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_StatsDebts {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.StatsDebts", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_AmountOfDebts {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.AmountOfDebts", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_RemainingDebts {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.RemainingDebts", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_TotalAmountDebts {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.TotalAmountDebts", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_CollectedDebts {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.CollectedDebts", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_StatsLoans {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.StatsLoans", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_AmountOfLoans {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.AmountOfLoans", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_TotalAmountOfLoans {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.TotalAmountOfLoans", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_RemainingAmountLoan {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.RemainingAmountLoan", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_PaidAmountLoan {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.PaidAmountLoan", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_General {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.General", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_PhoneNumber {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.PhoneNumber", resourceCulture);
            }
        }
        
        public static string ContactListViewModel_EmptyListText {
            get {
                return ResourceManager.GetString("ContactListViewModel.EmptyListText", resourceCulture);
            }
        }
        
        public static string ContactListViewModel_ImportContacts {
            get {
                return ResourceManager.GetString("ContactListViewModel.ImportContacts", resourceCulture);
            }
        }
        
        public static string ContactListViewModel_LoadMore {
            get {
                return ResourceManager.GetString("ContactListViewModel.LoadMore", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_General {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.General", resourceCulture);
            }
        }
        
        public static string BudgetDetailsViewModel_General {
            get {
                return ResourceManager.GetString("BudgetDetailsViewModel.General", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.Title", resourceCulture);
            }
        }
        
        public static string BudgetDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("BudgetDetailsViewModel.Title", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_Price {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.Price", resourceCulture);
            }
        }
        
        public static string BudgetDetailsViewModel_Price {
            get {
                return ResourceManager.GetString("BudgetDetailsViewModel.Price", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_Details {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.Details", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_OperationType {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.OperationType", resourceCulture);
            }
        }
        
        public static string BudgetDetailsViewModel_OperationType {
            get {
                return ResourceManager.GetString("BudgetDetailsViewModel.OperationType", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_CreatedDate {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.CreatedDate", resourceCulture);
            }
        }
        
        public static string BudgetDetailsViewModel_CreatedDate {
            get {
                return ResourceManager.GetString("BudgetDetailsViewModel.CreatedDate", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_PaymentDeadline {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.PaymentDeadline", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_CreatedAtLocation {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.CreatedAtLocation", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_TapToSeeOnMap {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.TapToSeeOnMap", resourceCulture);
            }
        }
        
        public static string FinanceDetailsViewModel_PaymentDate {
            get {
                return ResourceManager.GetString("FinanceDetailsViewModel.PaymentDate", resourceCulture);
            }
        }
        
        public static string BaseFinancesViewModel_LoadMore {
            get {
                return ResourceManager.GetString("BaseFinancesViewModel.LoadMore", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationViewModel_EnterAmountHint {
            get {
                return ResourceManager.GetString("AddFinanceOperationViewModel.EnterAmountHint", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationViewModel_EnterDeadlineHint {
            get {
                return ResourceManager.GetString("AddFinanceOperationViewModel.EnterDeadlineHint", resourceCulture);
            }
        }
        
        public static string AddContactViewModel_Title {
            get {
                return ResourceManager.GetString("AddContactViewModel.Title", resourceCulture);
            }
        }
        
        public static string AddContactViewModel_Content {
            get {
                return ResourceManager.GetString("AddContactViewModel.Content", resourceCulture);
            }
        }
        
        public static string AddContactViewModel_NameHint {
            get {
                return ResourceManager.GetString("AddContactViewModel.NameHint", resourceCulture);
            }
        }
        
        public static string AddContactViewModel_PhoneNumberHint {
            get {
                return ResourceManager.GetString("AddContactViewModel.PhoneNumberHint", resourceCulture);
            }
        }
        
        public static string AddContactViewModel_AddContactHint {
            get {
                return ResourceManager.GetString("AddContactViewModel.AddContactHint", resourceCulture);
            }
        }
        
        public static string AddBudgetViewModel_AddBudgetHint {
            get {
                return ResourceManager.GetString("AddBudgetViewModel.AddBudgetHint", resourceCulture);
            }
        }
        
        public static string AddBudgetViewModel_Title {
            get {
                return ResourceManager.GetString("AddBudgetViewModel.Title", resourceCulture);
            }
        }
        
        public static string AddBudgetViewModel_Content {
            get {
                return ResourceManager.GetString("AddBudgetViewModel.Content", resourceCulture);
            }
        }
        
        public static string AddBudgetViewModel_TitleHint {
            get {
                return ResourceManager.GetString("AddBudgetViewModel.TitleHint", resourceCulture);
            }
        }
        
        public static string PickContactViewModel_EmptyListText {
            get {
                return ResourceManager.GetString("PickContactViewModel.EmptyListText", resourceCulture);
            }
        }
        
        public static string PickContactViewModel_ImportContacts {
            get {
                return ResourceManager.GetString("PickContactViewModel.ImportContacts", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_BudgetText {
            get {
                return ResourceManager.GetString("StatisticsViewModel.BudgetText", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_DebtsText {
            get {
                return ResourceManager.GetString("StatisticsViewModel.DebtsText", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_AmountOfDebts {
            get {
                return ResourceManager.GetString("StatisticsViewModel.AmountOfDebts", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_AmountOfBudget {
            get {
                return ResourceManager.GetString("StatisticsViewModel.AmountOfBudget", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_TotalAmountOfDebtsMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.TotalAmountOfDebtsMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_TotalAmountOfBudget {
            get {
                return ResourceManager.GetString("StatisticsViewModel.TotalAmountOfBudget", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_RemainingAmountOfDebtMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.RemainingAmountOfDebtMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_Expenses {
            get {
                return ResourceManager.GetString("StatisticsViewModel.Expenses", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_CollectedAmountOfDebtMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.CollectedAmountOfDebtMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_Income {
            get {
                return ResourceManager.GetString("StatisticsViewModel.Income", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_LoanText {
            get {
                return ResourceManager.GetString("StatisticsViewModel.LoanText", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_AmountOfLoans {
            get {
                return ResourceManager.GetString("StatisticsViewModel.AmountOfLoans", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_TotalAmountOfLoanMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.TotalAmountOfLoanMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_RemainingAmountOfLoanMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.RemainingAmountOfLoanMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_PaidAmountOfLoanMoney {
            get {
                return ResourceManager.GetString("StatisticsViewModel.PaidAmountOfLoanMoney", resourceCulture);
            }
        }
        
        public static string StatisticsViewModel_StatisticsText {
            get {
                return ResourceManager.GetString("StatisticsViewModel.StatisticsText", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_FinanceOperations {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_FinanceOperations", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_BudgetAll {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_BudgetAll", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_BudgetExpenses {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_BudgetExpenses", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_BudgetIncome {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_BudgetIncome", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_All {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_All", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Debts {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Debts", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Loans {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Loans", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Favorites {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Favorites", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_General {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_General", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Contacts {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Contacts", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Statistics {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Statistics", resourceCulture);
            }
        }
        
        public static string MainBottomMenuFragment_Menu_Settings {
            get {
                return ResourceManager.GetString("MainBottomMenuFragment_Menu_Settings", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_FoodAndDrinks {
            get {
                return ResourceManager.GetString("Budget_Category_Main_FoodAndDrinks", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_Shopping {
            get {
                return ResourceManager.GetString("Budget_Category_Main_Shopping", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_House {
            get {
                return ResourceManager.GetString("Budget_Category_Main_House", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_Transport {
            get {
                return ResourceManager.GetString("Budget_Category_Main_Transport", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_Car {
            get {
                return ResourceManager.GetString("Budget_Category_Main_Car", resourceCulture);
            }
        }
        
        public static string Budget_Category_Main_Entertaiment {
            get {
                return ResourceManager.GetString("Budget_Category_Main_Entertaiment", resourceCulture);
            }
        }
        
        public static string Budget_Category_Electronics {
            get {
                return ResourceManager.GetString("Budget_Category_Electronics", resourceCulture);
            }
        }
        
        public static string Budget_Category_Bank {
            get {
                return ResourceManager.GetString("Budget_Category_Bank", resourceCulture);
            }
        }
        
        public static string Budget_Category_Investments {
            get {
                return ResourceManager.GetString("Budget_Category_Investments", resourceCulture);
            }
        }
        
        public static string Budget_Category_Income {
            get {
                return ResourceManager.GetString("Budget_Category_Income", resourceCulture);
            }
        }
        
        public static string Budget_Category_Other {
            get {
                return ResourceManager.GetString("Budget_Category_Other", resourceCulture);
            }
        }
        
        public static string Budget_Category_HealthBeauty {
            get {
                return ResourceManager.GetString("Budget_Category_HealthBeauty", resourceCulture);
            }
        }
        
        public static string Budget_Category_AlcoholSmoke {
            get {
                return ResourceManager.GetString("Budget_Category_AlcoholSmoke", resourceCulture);
            }
        }
        
        public static string Budget_Category_Education {
            get {
                return ResourceManager.GetString("Budget_Category_Education", resourceCulture);
            }
        }
        
        public static string Budget_Category_Hobby {
            get {
                return ResourceManager.GetString("Budget_Category_Hobby", resourceCulture);
            }
        }
        
        public static string Budget_Category_Books {
            get {
                return ResourceManager.GetString("Budget_Category_Books", resourceCulture);
            }
        }
        
        public static string Budget_Category_Sport {
            get {
                return ResourceManager.GetString("Budget_Category_Sport", resourceCulture);
            }
        }
        
        public static string Budget_Category_PhoneInternet {
            get {
                return ResourceManager.GetString("Budget_Category_PhoneInternet", resourceCulture);
            }
        }
        
        public static string Budget_Category_Taxes {
            get {
                return ResourceManager.GetString("Budget_Category_Taxes", resourceCulture);
            }
        }
        
        public static string CommonText_DONE {
            get {
                return ResourceManager.GetString("CommonText_DONE", resourceCulture);
            }
        }
        
        public static string DateDialog_PaymentDeadline_Title {
            get {
                return ResourceManager.GetString("DateDialog_PaymentDeadline_Title", resourceCulture);
            }
        }
        
        public static string ContactDetailsViewModel_UserHasNoPhoneNumber {
            get {
                return ResourceManager.GetString("ContactDetailsViewModel.UserHasNoPhoneNumber", resourceCulture);
            }
        }
        
        public static string EmptyFinanceSection_Text {
            get {
                return ResourceManager.GetString("EmptyFinanceSection_Text", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationNote_Title {
            get {
                return ResourceManager.GetString("AddFinanceOperationNote_Title", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationNote_Body {
            get {
                return ResourceManager.GetString("AddFinanceOperationNote_Body", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationNote_EnterPlaceholder {
            get {
                return ResourceManager.GetString("AddFinanceOperationNote_EnterPlaceholder", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationNote_Cancel {
            get {
                return ResourceManager.GetString("AddFinanceOperationNote_Cancel", resourceCulture);
            }
        }
        
        public static string AddFinanceOperationNote_Ok {
            get {
                return ResourceManager.GetString("AddFinanceOperationNote_Ok", resourceCulture);
            }
        }
        
        public static string DeepLink_SocialTags_Title {
            get {
                return ResourceManager.GetString("DeepLink_SocialTags_Title", resourceCulture);
            }
        }
        
        public static string DeepLink_SocialTags_Body {
            get {
                return ResourceManager.GetString("DeepLink_SocialTags_Body", resourceCulture);
            }
        }
        
        public static string ErrorLayerResponse_BuildDeepLink_ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorLayerResponse_BuildDeepLink_ErrorMessage", resourceCulture);
            }
        }
        
        public static string Premium_CantBuy {
            get {
                return ResourceManager.GetString("Premium_CantBuy", resourceCulture);
            }
        }
    }
}
